### ISSUE TITLE
Authz Oathkeeper zcap signing fails

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/edge-agent#580]
url - https://demo-oathkeeper-auth-keyserver.trustbloc.local:4461
error - {"error":{"code":401,"status":"Unauthorized","message":"The request could not be authorized"}}

**Comment by rolsonquadras** [comment]
@llorllale this issue seems to be related to the one we were discussing offline (wallet not having access_token).

**Comment by llorllale** [comment]
> @llorllale this issue seems to be related to the one we were discussing offline (wallet not having access_token).

I can confirm i have the same issue and is most likely due to that.
