### ISSUE TITLE
Sign the Verifiable Presentation and create QR Code

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/edge-agent#59]
-  sign the presentation. Code reference is in edge-service

**Comment by fqutishat** [comment]
@talwinder50 Create is DID is ready https://github.com/trustbloc/edge-agent/blob/e330b43cdd68915a867e58ad471bef1df988a5be/cmd/user-agent/src/views/CreateDID.vue#L24

**Comment by fqutishat** [comment]
@talwinder50 please remove create DID page after you finish this task

**Comment by fqutishat** [comment]
@troyronda @sandrask

**Comment by troyronda** [comment]
@talwinder50 @rolsonquadras @sudeshrshetty @fqutishat @sandrask 
How will the user create their public DID?

Also ... how do we allow the user to create a DID on another supported ledger network...

**Comment by fqutishat** [comment]
@talwinder50  don't remove create did page we just use it for Manage public DID

**Comment by talwinder50** [comment]
done
