### ISSUE TITLE
wallet-server: CHAPI bridge vs VC Wallet

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/edge-agent#651]
Current wallet-server can be used in 2 modes as per design.

- as VC Wallet : Universal wallet 2020 implementation which serves as a backend for wallet implementations Refer [aries design](https://wiki.hyperledger.org/display/ARIES/Aries+Framework+Go+Wallet)
- as CHAPI bridge: For integrating mobile app based wallets to issuer/rp CHAPI interfaces. Refer https://github.com/trustbloc/edge-agent/issues/633

Wallet-server has to be run in one of the above 2 modes. They can't co-exist in the single sever instance since VC wallet belongs to wallet implementation and CHAPI bridge belongs to rp/issuer implementation.

|VC wallet | CHAPI bridge |
| -------------- |-------------- |
| belongs to wallet implementation | belongs to rp/issuer implementation |
| exposes common reusable private components of wallet implementation | interfaces which acts as adapter to connect rp/issuer to remote wallet app (eg: mobile wallet app)|
| existing [wallet-server image](https://github.com/orgs/trustbloc-cicd/packages/container/package/wallet-server) can be extended | existing [rp-adapter-image](https://github.com/orgs/trustbloc-cicd/packages/container/package/rp-adapter) & [issuer-adapter-image](https://github.com/orgs/trustbloc-cicd/packages/container/package/issuer-adapter) can be extended |

**Conclusion**: extending current rp & issuer adapters to include interfaces for CHAPI bridge(create invitation, request profile & send CHAPI request) will avoid the burden of introducing one more container/server for issuer/rp each whenever they have to deal with mobile based wallets (as per existing design).
**new repo for chapi bridge**: https://github.com/trustbloc/edge-adapter
**additional interfaces**: `/create-invitation, /request-app-profile, /send-chapi-request`

**Comment by troyronda** [comment]
As discussed, please make generic rather than "chapi"-specific.
